version: "3.0"
services:
  static:
    image: nginx:1.25.3-alpine-slim
    container_name: nginx
    restart: unless-stopped
    networks:
      - default
      - webgateway
    volumes:
      - /home/ubuntu/devbox-store/static:/usr/share/nginx/html:ro
    labels:
      - traefik.docker.network=webgateway
      - "traefik.http.routers.static.rule=Host(`${DOMAIN}`) || Host(`${WKD_DOMAIN}`)"
      - traefik.http.routers.static.tls=true
      - traefik.http.routers.static.tls.certResolver=letsencrypt
      - "traefik.http.middlewares.corsheader.headers.accesscontrolallowmethods=GET"
      - "traefik.http.middlewares.corsheader.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.corsheader.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.corsheader.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.corsheader.headers.addvaryheader=true"
      - "traefik.http.routers.static.middlewares=corsheader"
      - traefik.http.services.static.loadbalancer.server.port=80
networks:
  webgateway:
    external: true
